name: APIdogCLI Test and Report
 
on: workflow_dispatch
 
jobs:
  apidog_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      # Step to run APIdog tests and save JSON report as an artifact
      - name: Run APIdog tests
        run: apidog run https://api.apidog.com/api/v1/projects/455055/api-test/ci-config/349135/detail?token=xrwGYepeqT3Yx1KYguS0Pt -r json,cli
        # This command runs APIdog tests and generates both CLI and JSON reports
 
      - name: Archive JSON report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: apidog_report
          path: path/to/apidog_report.json  # Adjust the path to the location of your JSON report file
