name: APIDog Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Apidog CLI
      run: npm install -g apidog-cli

    - name: Run APIDog tests
      run: |
        mkdir -p testArtifacts  # Create the directory if it doesn't exist
        apidog run -o testArtifacts/apidog_report.json https://api.apidog.com/api/v1/projects/455055/api-test/ci-config/349135/detail?token=xrwGYepeqT3Yx1KYguS0Pt -r html,cli

    - name: Upload APIDog reports
      uses: actions/upload-artifact@v2
      with:
        name: apidog-reports
        path: testArtifacts
