name: Simple Workflow

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, GitHub Actions!"
