name: Run Newman tests and generate HTML report
on: 
  workflow_dispatch:

jobs:
  test_and_generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Create testArtifacts directory
        run: mkdir -p testArtifacts

      - name: Run APIdog tests and generate HTML report
        run: |
          apidog run https://api.apidog.com/api/v1/projects/455055/api-test/ci-config/349135/detail?token=xrwGYepeqT3Yx1KYguS0Pt -r html
      
      - name: Convert HTML report to HTML Extra (htmlextra)
        run: |
          newman run ${{ github.workspace }}/testArtifacts/apidog_report*.html -r htmlextra --reporter-htmlextra-export testArtifacts/report.htmlextra

      - name: Output the results
        uses: actions/upload-artifact@v3
        with: 
          name: Reports
          path: ${{ github.workspace }}/testArtifacts/
      - name: Send email with HTML report
        run: node sendEmail.js
        env:
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
