name: Run API tests and generate HTML report
on: 
  workflow_dispatch:

jobs:
  test_and_generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Create testArtifacts directory
        run: mkdir -p testArtifacts
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run API tests and generate HTML report
        run: |
          newman run https://api.apidog.com/api/v1/projects/455055/api-test/ci-config/349133/detail?token= -r htmlextra
      
      - name: Output the results
        uses: actions/upload-artifact@v3
        with: 
          name: Reports
          path: ${{ github.workspace }}/testArtifacts/

      - name: Send email with HTML report
        run: node sendEmail.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
