name: Run APIdog Tests

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install APIdog CLI
      run: npm install -g apidog-cli

    - name: Run APIdog tests
      run: apidog run https://api.apidog.com/api/v1/projects/123456/api-test/ci-config/789012/detail?token=YOUR_TOKEN -r cli,html
