name: Run APIdog tests and generate HTML Extra (htmlextra) report
on: 
  workflow_dispatch:

jobs:
  test_and_generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install SendGrid library
        run: npm install @sendgrid/mail
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install APIdog CLI
        run: npm install -g apidog-cli
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run APIdog tests and generate HTML report
        run: |
          apidog run https://api.apidog.com/api/v1/projects/455055/api-test/ci-config/349135/detail?token=xrwGYepeqT3Yx1KYguS0Pt -r html

      - name: Find dynamically generated APIdog report file
        id: find-report
        run: |
          report_file=$(find "${{ github.workspace }}/apidog-reports/" -type f -name "apidog-report-*.html" -printf "%T@ %p\n" | sort -nr | head -n1 | cut -d ' ' -f2)
          echo "::set-output name=report_path::$report_file"

      - name: Run Newman with HTML report
        run: |
          newman run "${{ steps.find-report.outputs.report_path }}" -r htmlextra --reporter-htmlextra-export "${{ steps.find-report.outputs.report_path }}_report.htmlextra"

      - name: Output the results
        uses: actions/upload-artifact@v3
        with: 
          name: Reports
          path: ${{ steps.find-report.outputs.report_path }}.htmlextra

      - name: Send email with HTML report
        run: node sendEmail.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
