name: Run API tests and generate HTML report
on: 
  workflow_dispatch:

jobs:
  test_and_generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Create testArtifacts directory
        run: mkdir -p testArtifacts
      
      - name: Run API tests and generate HTML report
        run: |
          newman run https://api.apidog.com/api/v1/projects/455055/api-test/ci-config/349135/detail?token=xrwGYepeqT3Yx1KYguS0Pt --reporter-htmlextra-export testArtifacts/report.html
      
      - name: Output the results
        uses: actions/upload-artifact@v3
        with: 
          name: Reports
          path: ${{ github.workspace }}/testArtifacts/
