name: Run APIdog Tests
on: workflow_dispatch

jobs:
  test_and_send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SendGrid library
        run: npm install @sendgrid/mail
      
      - name: Create testArtifacts directory
        run: mkdir TestArtifacts
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install APIdog CLI
        run: npm install -g apidog-cli
      
      - name: Run APIdog tests and generate JSON report
        run: |
          curl -o testArtifacts/apidog_report.json "https://api.apidog.com/api/v1/projects//api-test/ci-config//detail?token=" && \
          apidog run https://api.apidog.com/api/v1/projects//api-test/ci-config//detail?token= -r cli
      
      - name: Convert JSON to HTML
        run: node convertToJsonToHtml.js testArtifacts/apidog_report.json testArtifacts/apidog_report.html
      
      - name: Output the results
        uses: actions/upload-artifact@v3
        with: 
          name: Reports
          path: testArtifacts
      
      - name: Send email with HTML report
        run: node sendEmail.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
