name: Run APIdog Tests and Send Email

on:
  workflow_dispatch

jobs:
  test_and_send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SendGrid library
        run: npm install @sendgrid/mail

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update Newman to latest version
        run: npm install -g newman@latest

      - name: Install APIdog CLI
        run: npm install -g apidog-cli

      - name: Install Newman and HTML reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run APIdog tests and generate Newman HTML report
        run: |
          apidog run https://api.apidog.com/api/v1/projects/455055/api-test/ci-config/350185/detail?token=x8TGslzNjbHS-cFqe8gMec -r json
          newman run $(find . -name 'apidog-report-*.json') --reporters cli,htmlextra --reporter-htmlextra-export newman-report.html

      - name: Send email with Newman HTML report
        run: node sendEmail.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
