name: PostmanEmail
on: workflow_dispatch

jobs:
    test-api:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Create dir
              run: |
                mkdir  TestArtifacts

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: '16.x'

            - name: Install Newman
              run: |
                npm install -g newman
                npm install -g newman-reporter-slackreporter
                npm install -g newman-reporter-htmlextra

            - name: Run Tests
              run: newman run "SDET-QA.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html

            - name: Output the results
              uses: actions/upload-artifact@v3
              with: 
                name: Reports
                path: testArtifacts
   
    #send_email:
 
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                name: test-results  # Name of the artifact containing your reports
                path: reports  # Directory to download the artifact
        
            - name: Send email with reports
              uses: sendgrid/email-action@1.3.1
              env:
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}  # SendGrid API key
              with:
                to: nandakumarap@anthology.com  # Email recipient
                from: ivpnotifications@products.anthology.com  # Your email address
                subject: Test Reports
                text: Please find attached the test reports.
                attachments: |
                  reports/*
