name: Send Email with Reports

on: workflow_dispatch

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: test-results  # Name of the artifact containing your reports
        path: reports  # Directory to download the artifact

    - name: Send email with reports
      uses: sendgrid/email-action@1.3.1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}  # SendGrid API key
      with:
        to: nandakumarap@anthology.com  # Email recipient
        from: ivpnotifications@products.anthology.com  # Your email address
        subject: Test Reports
        text: Please find attached the test reports.
        attachments: |
          reports/*
